import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import logo from '../../../assets/logo'; // Ensure this is a valid base64 string

const generatePaymentSuccessPDF = (paymentDetails, filename, userName) => {
    const doc = new jsPDF();

    // Dimensions and positions
    const pageWidth = doc.internal.pageSize.getWidth();
    const imgWidth = 80; // Logo width
    const imgHeight = 20; // Logo height
    const xPos = (pageWidth - imgWidth) / 2; // Center horizontally
    const yPos = 10; // Position near the top of the page

    // Add logo
    doc.addImage(logo, 'PNG', xPos, yPos, imgWidth, imgHeight);

    // Add a line below the logo
    const lineY = yPos + imgHeight + 5; // Position for the line
    doc.setDrawColor(0);
    doc.setLineWidth(0.5);
    doc.line(10, lineY, pageWidth - 10, lineY); // Line below logo

    // Add spacing
    let yPosition = lineY + 10; // Space after line

    // Add success text
    doc.setFontSize(16);
    doc.setTextColor(50, 50, 50);
    doc.text("Payment Success", 10, yPosition);
    yPosition += 10; // Space after title

    // Prepare table data
    const tableData = [
        { label: "Order ID", value: paymentDetails.orderId },
        { label: "Email", value: paymentDetails.email },
        { label: "Phone", value: paymentDetails.phone },
        { label: "Address", value: paymentDetails.address },
        { label: "City", value: paymentDetails.city },
        { label: "Country", value: paymentDetails.country },
        { label: "Amount", value: `LKR ${paymentDetails.amount}` },
    ];

    // Generate the table
    const columns = [
        { header: 'Field', dataKey: 'label' },
        { header: 'Value', dataKey: 'value' }
    ];

    // Here, we can use tableData as it is already an array
    doc.autoTable({
        columns,
        body: tableData,
        startY: yPosition,
        margin: { top: 20 },
    });

    // Add autogenerated text at the bottom of the page
    const autoGenText = `This is an autogenerated PDF for ${userName} from Ceylon Odyssey on ${new Date().toLocaleDateString()}`;
    const autoGenYPos = doc.internal.pageSize.height - 20; // Position near the bottom
    doc.setTextColor(150, 150, 150); // Lighter color for autogenerated text
    doc.text(autoGenText, 10, autoGenYPos);

    // Save the document
    doc.save(filename);
};

export default generatePaymentSuccessPDF;